/*
 * Source-only structural mirror of the JavaScript API generated by napi-rs from
 * the Metal Rust exports. The adapter imports these declarations with `import
 * type`; the loader's NativeAddon assertion performs no runtime validation, so
 * this file must stay in lockstep with the native ABI. `stripInternal` keeps the
 * declarations out of the public entry-point surface, and the package build
 * removes internal `.d.ts` files plus this file's empty emitted `.js`; consumers
 * receive only `dist/index.d.ts`, while `adapter.js` talks directly to the addon.
 */
/** Cooperative token polled by asynchronous native work. @internal */
export declare class CancellationToken {
  constructor()
  cancel(): void
  get cancelled(): boolean
}

/**
 * Immutable compiled native artifact. Geometry getters are zero for stateless
 * programs; `diagnostics` describes the frozen plan. `execute` borrows inputs
 * and sequences until its Promise settles and returns newly owned tensor
 * wrappers. Stateful execution requires paired sequence/token arrays, rejects
 * scalar inputs, and commits sequence updates only on success. `executeSampled`
 * follows the same stateful transaction but returns one token per active output
 * without creating output tensor wrappers.
 *
 * @internal
 */
export declare class Executable {
  get stateful(): boolean
  get batch(): number
  get packedRowsPerSequence(): number | undefined
  get allowsWindowEviction(): boolean
  get layers(): number
  get kvHeads(): number
  get headDim(): number
  get kdaLayers(): number
  get kdaHeads(): number
  get kdaHeadDim(): number
  get kdaValueDim(): number
  get convLayers(): number
  get convChannels(): number
  get convKernel(): number
  get diagnostics(): NativeExecutableDiagnostics
  execute(
    inputs: Array<NativeTensor>,
    scalars: Array<number>,
    sequences?: Array<NativeKvSequence> | undefined | null,
    slots?: Array<number> | undefined | null,
    activeMask?: Array<boolean> | undefined | null,
    validLengths?: Array<number> | undefined | null,
    advances?: Array<number> | undefined | null,
    tokens?: Array<Array<number>> | undefined | null,
    token?: CancellationToken | undefined | null
  ): Promise<Array<NativeTensor>>
  executeSampled(
    inputs: Array<NativeTensor>,
    sequences: Array<NativeKvSequence>,
    slots: Array<number>,
    activeMask: Array<boolean>,
    validLengths: Array<number>,
    advances: Array<number>,
    tokens: Array<Array<number>>,
    sampling: Array<NativeSamplingOptions>,
    token?: CancellationToken | undefined | null
  ): Promise<Array<number>>
  executeSpeculative(
    proposer: Executable,
    targetSequences: Array<NativeKvSequence>,
    proposerSequences: Array<NativeKvSequence>,
    slots: Array<number>,
    pendingTokens: Array<number>,
    sampling: Array<NativeSamplingOptions>,
    maxDraftTokens: number,
    pageLimits: Array<number>,
    eosTokens: Array<Array<number>>,
    token?: CancellationToken | undefined | null
  ): Promise<Array<Array<number>>>
}

/**
 * Native semantic-graph node. Constructors and methods build graph structure
 * synchronously; they do not materialize tensors. `fromMaterialized` retains a
 * reference to the source wrapper's leaf slot, so clearing that wrapper also
 * invalidates dependent graph use even if another alias retains the allocation.
 *
 * @internal
 */
export declare class LazyTensor {
  get shape(): Array<number>
  get dtype(): string
  metadata(): [Array<number>, string]
  static zeros(shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static ones(shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static full(shape: Array<number>, value: number, dtype?: NativeDType | undefined | null): LazyTensor
  static randn(shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static uniform(shape: Array<number>, lo: number, hi: number, dtype?: NativeDType | undefined | null): LazyTensor
  static arange(start: number, end: number, step: number, dtype?: NativeDType | undefined | null): LazyTensor
  static eye(n: number, dtype?: NativeDType | undefined | null): LazyTensor
  static constant(value: number, dtype?: NativeDType | undefined | null): LazyTensor
  static fromBytes(data: Uint8Array, shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static fromMaterialized(tensor: NativeTensor): LazyTensor
  static input(slot: number, shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static scalarInput(slot: number, dtype?: NativeDType | undefined | null): LazyTensor
  add(other: LazyTensor): LazyTensor
  sub(other: LazyTensor): LazyTensor
  mul(other: LazyTensor): LazyTensor
  div(other: LazyTensor): LazyTensor
  maximum(other: LazyTensor): LazyTensor
  minimum(other: LazyTensor): LazyTensor
  eq(other: LazyTensor): LazyTensor
  gt(other: LazyTensor): LazyTensor
  lt(other: LazyTensor): LazyTensor
  ge(other: LazyTensor): LazyTensor
  le(other: LazyTensor): LazyTensor
  matmul(other: LazyTensor): LazyTensor
  inverse(): LazyTensor
  det(): LazyTensor
  solve(other: LazyTensor): LazyTensor
  neg(): LazyTensor
  abs(): LazyTensor
  sqrt(): LazyTensor
  exp(): LazyTensor
  tanh(): LazyTensor
  gelu(approximate?: boolean | undefined | null): LazyTensor
  relu(): LazyTensor
  erf(): LazyTensor
  floor(): LazyTensor
  ceil(): LazyTensor
  round(): LazyTensor
  sign(): LazyTensor
  whereCond(a: LazyTensor, b: LazyTensor): LazyTensor
  argmax(dim: number): LazyTensor
  argmin(dim: number): LazyTensor
  cumsum(dim: number): LazyTensor
  indexSelect(dim: number, indexes: LazyTensor): LazyTensor
  scatterAdd(dim: number, indexes: LazyTensor, src: LazyTensor): LazyTensor
  gather(dim: number, indexes: LazyTensor): LazyTensor
  crossEntropy(target: LazyTensor, ignoreIndex: number): LazyTensor
  scaledDotProductAttention(k: LazyTensor, v: LazyTensor, scale: number, causal: boolean, window: number): LazyTensor
  kdaChunk(k: LazyTensor, v: LazyTensor, logDecay: LazyTensor, beta: LazyTensor, scale: number): LazyTensor
  shortConv1d(weight: LazyTensor): LazyTensor
  positionEmbedding(seqLen: number): LazyTensor
  rotaryEmbedding(seqLen: number, theta: number, layout: NativeRotaryLayout): LazyTensor
  layerNorm(weight: LazyTensor, bias: LazyTensor, eps: number): LazyTensor
  rmsNorm(weight: LazyTensor | undefined, eps: number): LazyTensor
  linear(weight: LazyTensor, bias: LazyTensor): LazyTensor
  quantizedLinear(
    weight: LazyTensor,
    bias: LazyTensor | undefined | null,
    encoding: NativeGgmlKQuant,
    rows: number,
    columns: number
  ): LazyTensor
  quantizedEmbedding(
    weight: LazyTensor,
    encoding: NativeGgmlKQuant,
    rows: number,
    columns: number,
    paddingIndex?: number | undefined | null
  ): LazyTensor
  conv1d(w: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  conv2d(w: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  log(): LazyTensor
  sin(): LazyTensor
  cos(): LazyTensor
  pow(exp: number): LazyTensor
  cast(dtype: NativeDType): LazyTensor
  sum(dims: Array<number>, keepdims: boolean): LazyTensor
  prod(dims: Array<number>, keepdims: boolean): LazyTensor
  mean(dims: Array<number>, keepdims: boolean): LazyTensor
  max(dims: Array<number>, keepdims: boolean): LazyTensor
  min(dims: Array<number>, keepdims: boolean): LazyTensor
  reshape(shape: Array<number>): LazyTensor
  permute(dims: Array<number>): LazyTensor
  slice(ranges: Array<Array<number>>): LazyTensor
  concat(other: LazyTensor, dim: number): LazyTensor
  broadcastTo(shape: Array<number>): LazyTensor
  stopGradient(): LazyTensor
  checkpoint(): LazyTensor
  vmap(x: LazyTensor, batchedX: LazyTensor, dim: number): LazyTensor
  adamwStep(
    grad: LazyTensor,
    m: LazyTensor,
    v: LazyTensor,
    lr: LazyTensor,
    c1: LazyTensor,
    c2: LazyTensor,
    beta1: number,
    beta2: number,
    eps: number,
    weightDecay: number
  ): LazyTensor
  adamwOut(index: number): LazyTensor
  sgdStep(
    grad: LazyTensor,
    velocity: LazyTensor,
    first: LazyTensor,
    lr: LazyTensor,
    momentum: number,
    dampening: number,
    nesterov: boolean,
    weightDecay: number
  ): LazyTensor
  sgdOut(index: number): LazyTensor
}

/**
 * Native owner of fixed-capacity paged-KV slabs and prefix-cache state.
 * Recurrent geometry is pool-wide, but recurrent buffers are allocated per
 * sequence.
 *
 * @internal
 */
export declare class NativeKvPool {
  constructor(
    layers: number,
    kvHeads: number,
    headDim: number,
    maxTokens: number,
    blockSize?: number | undefined | null,
    dtype?: NativeDType | undefined | null,
    recurrent?: NativeRecurrentStateSchema | undefined | null
  )
  get capacity(): number
  get freeBlocks(): number
  get cachedBlocks(): number
  makeSequence(): NativeKvSequence
}

/**
 * Native sequence leased from one pool. It retains KV block references and
 * per-sequence recurrent buffers. `release` idempotently invalidates it and
 * returns its block references; recurrent buffers remain until finalization.
 *
 * @internal
 */
export declare class NativeKvSequence {
  get cursor(): number
  release(): void
  prefillMatch(tokens: Array<number>): number
}

/** Immutable validated bundle used to open cohesive native inference sessions. @internal */
export declare class NativeInferenceArtifact {
  constructor(
    targetPrefill: Executable,
    targetDecode: Executable,
    targetVerify: Executable | undefined | null,
    targetPool: NativeKvPool,
    proposerPrefill: Executable | undefined | null,
    proposerDecode: Executable | undefined | null,
    proposerPool: NativeKvPool | undefined | null,
    maxDraftTokens: number | undefined | null,
    batchSize: number,
    tokenDtype: NativeDType,
    sampling: NativeInferenceSamplingOptions,
    proposerPlan?: NativeProposerPlan | undefined | null,
    stageExecutables?: Array<Executable> | undefined | null,
    sharedTargetTensors?: Array<NativeTensor> | undefined | null
  )
  open(): NativeInferenceSession
  get inferenceDiagnostics(): NativeInferenceDiagnostics
}

/** Device-resident source for a generalized proposer stage binding. @internal */
export interface NativeValueRef {
  kind: "PendingTokens" | "CandidatePrefix" | "CommittedHistory" | "TargetHidden" | "SharedBinding" | "StageOutput"
  layer?: number
  binding?: number
  stage?: number
  output?: number
  /** Optional leading logical row. Non-zero rows are copied on device when a binding requires offset zero. */
  row?: number
  /** Select the active target lane when the native DAG helper executes. */
  selectRow?: boolean
}

/** Exact logical metadata retained for a routed value. @internal */
export interface NativeProposerValueSchema {
  shape: Array<number>
  dtype: NativeDType
}

/** One target output root exported as an ephemeral hidden activation. @internal */
export interface NativeTargetHiddenTap extends NativeProposerValueSchema {
  layer: number
  output: number
}

/** One immutable target tensor available through a named ValueRef. @internal */
export interface NativeSharedTargetBinding extends NativeProposerValueSchema {
  kind: "TokenEmbedding" | "LmHead"
  name: string
  tensor: number
}

/** Explicit stage input route. @internal */
export interface NativeStageInputBinding {
  slot: number
  value: NativeValueRef
}

/** One executable in the generalized proposer DAG. @internal */
export interface NativeProposerStage {
  executable?: number
  operationId: string
  layoutId?: string
  historyLookup?: {
    id: "suffix-ngram-v1"
    minMatchTokens: number
    maxMatchTokens: number
  }
  inputs: Array<NativeStageInputBinding>
  outputs: Array<NativeProposerValueSchema>
}

/** Stateful publication recipe retained with the proposer DAG. @internal */
export interface NativeProposerStatePlan {
  kind: "None" | "Kv"
  schemaId?: string
}

/** Explicit state commit recipe. @internal */
export interface NativeProposerCommitPlan {
  kind: "AutoregressiveChain" | "Replay"
  stage?: number
  stages?: Array<number>
}

/** Values exported by the proposer DAG. @internal */
export interface NativeProposerOutputPlan {
  topology: "Chains" | "Trees"
  probabilities: "CausalNormalized" | "Deterministic" | "Unavailable"
  tokenIds: NativeValueRef
  probabilityRows?: NativeValueRef
  parents?: NativeValueRef
  confidence?: NativeValueRef
}

/** Vocabulary translation retained by a generalized proposer artifact. @internal */
export interface NativeTokenMapPlan {
  kind: "Identity" | "Table"
  fingerprint: string
  proposerVocabulary?: number
  targetIds?: Array<number>
}

/** Optional trailing constructor plan for native target-coupled proposer stages. @internal */
export interface NativeProposerPlan {
  targetPrefillTaps: Array<NativeTargetHiddenTap>
  targetDecodeTaps: Array<NativeTargetHiddenTap>
  targetVerifyTaps: Array<NativeTargetHiddenTap>
  sharedTargetBindings: Array<NativeSharedTargetBinding>
  stages: Array<NativeProposerStage>
  state: NativeProposerStatePlan
  commit?: NativeProposerCommitPlan
  output: NativeProposerOutputPlan
  tokenMap: NativeTokenMapPlan
  trainedMaxRows: number
}

/** Native owner of lanes, paired KV state, policy, and durable receipts. @internal */
export declare class NativeInferenceSession {
  add(
    prompts: Array<NativeTensor>,
    sampling: Array<NativeInferenceSamplingOverride>,
    maxTokens: Array<number | undefined>,
    eosTokens: Array<Array<number>>,
    token?: CancellationToken | undefined | null
  ): Promise<NativeInferenceRoundResult>
  runRound(
    sequences: Array<NativeInferenceSequence>,
    sampling: Array<NativeInferenceSamplingOverride>,
    token?: CancellationToken | undefined | null
  ): Promise<NativeInferenceRoundResult>
  acknowledge(roundId: bigint): void
  sequence(sequenceId: bigint): NativeInferenceSequence
  finish(sequences: Array<NativeInferenceSequence>): void
  inspect(sequence: NativeInferenceSequence): NativeInferenceInspection
  close(): void
}

/** Session-provenanced native sequence identity. @internal */
export declare class NativeInferenceSequence {
  get sequenceId(): bigint
}

/** Lossless cohesive-inference sampling controls. @internal */
export interface NativeInferenceSamplingOptions {
  temperature: number
  topK: number
  topP: number
  seed: bigint
}

/** Partial controls resolved against artifact/lane policy by native code. @internal */
export interface NativeInferenceSamplingOverride {
  temperature?: number
  topK?: number
  topP?: number
  seed?: bigint
}

/** Native token page; the adapter restores its canonical opaque handle. @internal */
export interface NativeInferencePage {
  sequenceId: bigint
  tokens: Array<number>
  stopReason?: "eos" | "maxTokens"
}

/** Durable native result retained until `acknowledge`. @internal */
export interface NativeInferenceRoundResult {
  roundId: bigint
  recovered: boolean
  pages: Array<NativeInferencePage>
}

/** Native sequence policy/state inspection. @internal */
export interface NativeInferenceInspection {
  sequenceId: bigint
  cursor: bigint
  terminal?: "eos" | "maxTokens"
}

/** Artifact-wide cohesive inference counters. @internal */
export interface NativeInferenceDiagnostics {
  roundsStarted: bigint
  roundsCompleted: bigint
  roundsRecovered: bigint
  ordinaryRounds: bigint
  speculativeRounds: bigint
  proposedTokens: bigint
  acceptedTokens: bigint
  emittedTokens: bigint
  provisionalBlocks: bigint
  rolledBackBlocks: bigint
  draftNanos: bigint
  verificationNanos: bigint
  acceptedLengthHistogram: Array<bigint>
  targetPoolHighWaterBlocks: bigint
  proposerPoolHighWaterBlocks?: bigint
  lastRoundId?: bigint
  lastFailurePhase?: string
}

/** Owning JavaScript wrapper for one materialized Metal tensor. @internal */
export declare class NativeTensor {
  /**
   * Clears this wrapper's leaf slot instead of waiting for finalization. The
   * adapter turns subsequent use of its public handle into `invalid-handle`;
   * native graphs that captured the cleared leaf also fail when evaluated.
   * Other native aliases may continue retaining the underlying allocation.
   */
  clear(): void
  get shape(): Array<number>
  get dtype(): string
  get device(): string
  readback(token?: CancellationToken | undefined | null): Promise<ArrayBuffer>
  sample(
    temperature: number,
    topK: number,
    topP: number,
    seed: number,
    counter: number,
    cancellationToken?: CancellationToken | undefined | null
  ): Promise<number>
}

/**
 * Synchronously specializes and compiles nonempty roots, including Metal
 * pipeline preparation. The optional cache key addresses the addon's bounded
 * structural cache; native signatures are still revalidated, and
 * constant-weight compilation bypasses cache reuse.
 *
 * @internal
 */
export declare function compile(
  roots: Array<LazyTensor>,
  options?: NativeCompileOptions | undefined | null,
  state?: NativeKvStateSchema | undefined | null,
  cacheKey?: string | undefined | null
): Executable

/** Current bytes attributed to live native tensor wrappers. @internal */
export declare function externalMemoryBytes(): number

/** Synchronously constructs reverse-mode graph roots in `wrt` order. @internal */
export declare function grad(loss: LazyTensor, wrt: Array<LazyTensor>): Array<LazyTensor>

/** Probes whether a Metal device can create the required queue and event. @internal */
export declare function isAvailable(): boolean

/** Loads a safetensors archive into newly owned Metal tensor wrappers. @internal */
export declare function loadTensors(
  path: string,
  token?: CancellationToken | undefined | null
): Promise<NativeSafetensorsArchive>

/** GGML K-quant formats preserved as packed u8 native storage. @internal */
export type NativeGgmlKQuant = "Q2_K" | "Q3_K" | "Q4_K" | "Q5_K" | "Q6_K"

/**
 * N-API representation of one GGUF tagged metadata value. Exactly one value
 * field is populated; array element type is carried by `kind`.
 *
 * @internal
 */
export interface NativeGgufMetadataEntry {
  key: string
  kind: string
  numberValue?: number
  stringValue?: string
  booleanValue?: boolean
  numberArray?: Array<number>
  stringArray?: Array<string>
  booleanArray?: Array<boolean>
}

/** Logical f32 and physical Metal-storage geometry for one GGUF tensor. @internal */
export interface NativeGgufTensorDescriptor {
  name: string
  format: "F32" | NativeGgmlKQuant
  logicalShape: Array<number>
  logicalDtype: "f32"
  physicalShape: Array<number>
  physicalDtype: "f32" | "u8"
}

/** Header metadata and tensor catalog without payload allocation. @internal */
export interface NativeGgufInspection {
  metadata: Array<NativeGgufMetadataEntry>
  tensors: Array<NativeGgufTensorDescriptor>
}

/** Newly owned GGUF payload wrappers paired with their descriptors. @internal */
export interface NativeGgufArchive {
  entries: Array<{ descriptor: NativeGgufTensorDescriptor; tensor: NativeTensor }>
}

/** Parses and validates GGUF metadata/catalog without loading payloads. @internal */
export declare function inspectGguf(
  path: string,
  token?: CancellationToken | undefined | null
): Promise<NativeGgufInspection>

/** Streams supported GGUF F32 and packed K-quant payloads into Metal storage. @internal */
export declare function loadGguf(
  path: string,
  token?: CancellationToken | undefined | null
): Promise<NativeGgufArchive>

/** String enum emitted by napi-rs for the native dtype ABI. @internal */
export declare const enum NativeDType {
  F32 = "f32",
  F64 = "f64",
  I64 = "i64",
  U8 = "u8",
  U32 = "u32",
  F16 = "f16",
  BF16 = "bf16"
}

/** Native spelling of the two supported rotary coordinate layouts. @internal */
export type NativeRotaryLayout = "HalfSplit" | "InterleavedPairs"

/** Explicit native compiler overrides; omitted members use native defaults. @internal */
export interface NativeCompileOptions {
  optimize?: boolean
  constantWeights?: boolean
}

/** Normalized controls for one output sampled by fused decode execution. @internal */
export interface NativeSamplingOptions {
  temperature: number
  topK: number
  topP: number
  seed: number
  counter: number
}

/** Decode specialization request passed to native compilation. @internal */
export interface NativeKvStateSchema {
  maxTokens: number
  blockSize: number
  kvDtype: NativeDType
  window?: number
  batch: number
  packedCausalChains?: { rowsPerSequence: number }
  lastTokenRow?: boolean
}

/** Optional per-sequence recurrent geometry allocated beside KV state. @internal */
export interface NativeRecurrentStateSchema {
  kdaLayers: number
  kdaHeads: number
  kdaHeadDim: number
  kdaValueDim: number
  convLayers: number
  convChannels: number
  convKernel: number
}

/**
 * Static counters, memory-plan totals, and observed compile timings copied from
 * the immutable native artifact. These are not current allocation metrics.
 *
 * @internal
 */
export interface NativeExecutableDiagnostics {
  semanticNodesBeforeOptimization: number
  semanticNodesAfterOptimization: number
  instructions: Array<{ kind: string; count: number }>
  pipelineCount: number
  commandCount: number
  synchronizationCount: number
  memory: {
    externalBytes: number
    persistentBytes: number
    stateBytes: number
    outputBytes: number
    workspaceBytes: number
    transactionBytes: number
    peakLiveBytes: number
    packingOverheadBytes: number
  }
  compilePhases: Array<{ phase: string; nanoseconds: number }>
}

/** Newly owned safetensors entries plus string metadata. @internal */
export interface NativeSafetensorsArchive {
  entries: Array<NativeSafetensorsEntry>
  metadata: Record<string, string>
}

/** One newly owned tensor wrapper loaded from safetensors. @internal */
export interface NativeSafetensorsEntry {
  name: string
  tensor: NativeTensor
}

/**
 * Atomically writes borrowed dense tensors and string metadata. Native wrappers
 * remain owned by the caller after the Promise settles.
 *
 * @internal
 */
export declare function saveTensors(
  path: string,
  names: Array<string>,
  tensors: Array<NativeTensor>,
  metadata: Record<string, string>,
  token?: CancellationToken | undefined | null
): Promise<void>

/** Complete runtime shape asserted over the object returned by `require`. @internal */
export interface NativeAddon {
  readonly CancellationToken: typeof CancellationToken
  readonly Executable: typeof Executable
  readonly LazyTensor: typeof LazyTensor
  readonly NativeKvPool: typeof NativeKvPool
  readonly NativeKvSequence: typeof NativeKvSequence
  readonly NativeInferenceArtifact: typeof NativeInferenceArtifact
  readonly NativeInferenceSession: typeof NativeInferenceSession
  readonly NativeInferenceSequence: typeof NativeInferenceSequence
  readonly NativeTensor: typeof NativeTensor
  readonly compile: typeof compile
  readonly externalMemoryBytes: typeof externalMemoryBytes
  readonly grad: typeof grad
  readonly isAvailable: typeof isAvailable
  readonly inspectGguf: typeof inspectGguf
  readonly loadGguf: typeof loadGguf
  readonly loadTensors: typeof loadTensors
  readonly saveTensors: typeof saveTensors
}
