/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CancellationToken {
  constructor()
  cancel(): void
  get cancelled(): boolean
}

export declare class CompiledProgram {
  get signature(): string
  dispose(): void
  run(inputs: Array<NativeTensor>, scalars: Array<number>, token?: CancellationToken | undefined | null): Promise<Array<NativeTensor>>
}

export declare class DecodeProgram {
  get signature(): string
  get layers(): number
  get kvHeads(): number
  get headDim(): number
  dispose(): void
  run(inputs: Array<NativeTensor>, seq: NativeKvSequence, tokens: Array<number>, token?: CancellationToken | undefined | null): Promise<Array<NativeTensor>>
}

export declare class LazyTensor {
  dispose(): void
  get shape(): Array<number>
  get dtype(): string
  static zeros(shape: Array<number>, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static ones(shape: Array<number>, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static full(shape: Array<number>, value: number, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static randn(shape: Array<number>, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static uniform(shape: Array<number>, lo: number, hi: number, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static arange(start: number, end: number, step: number, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static eye(n: number, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static constant(value: number, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static fromBytes(data: Uint8Array, shape: Array<number>, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static fromMaterialized(tensor: NativeTensor): LazyTensor
  static input(slot: number, shape: Array<number>, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  static scalarInput(slot: number, dtype?: NativeDType | undefined | null, device?: string | undefined | null): LazyTensor
  add(other: LazyTensor): LazyTensor
  sub(other: LazyTensor): LazyTensor
  mul(other: LazyTensor): LazyTensor
  div(other: LazyTensor): LazyTensor
  maximum(other: LazyTensor): LazyTensor
  minimum(other: LazyTensor): LazyTensor
  eq(other: LazyTensor): LazyTensor
  gt(other: LazyTensor): LazyTensor
  lt(other: LazyTensor): LazyTensor
  ge(other: LazyTensor): LazyTensor
  le(other: LazyTensor): LazyTensor
  matmul(other: LazyTensor): LazyTensor
  inverse(): LazyTensor
  det(): LazyTensor
  solve(other: LazyTensor): LazyTensor
  neg(): LazyTensor
  abs(): LazyTensor
  sqrt(): LazyTensor
  exp(): LazyTensor
  tanh(): LazyTensor
  relu(): LazyTensor
  erf(): LazyTensor
  floor(): LazyTensor
  ceil(): LazyTensor
  round(): LazyTensor
  sign(): LazyTensor
  whereCond(a: LazyTensor, b: LazyTensor): LazyTensor
  argmax(dim: number): LazyTensor
  argmin(dim: number): LazyTensor
  cumsum(dim: number): LazyTensor
  indexSelect(dim: number, indexes: LazyTensor): LazyTensor
  scatterAdd(dim: number, indexes: LazyTensor, src: LazyTensor): LazyTensor
  gather(dim: number, indexes: LazyTensor): LazyTensor
  crossEntropy(target: LazyTensor, ignoreIndex: number): LazyTensor
  scaledDotProductAttention(k: LazyTensor, v: LazyTensor, scale: number, causal: boolean): LazyTensor
  positionEmbedding(seqLen: number): LazyTensor
  rotaryEmbedding(seqLen: number, theta: number): LazyTensor
  conv1d(w: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  conv2d(w: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  log(): LazyTensor
  sin(): LazyTensor
  cos(): LazyTensor
  pow(exp: number): LazyTensor
  cast(dtype: NativeDType): LazyTensor
  sum(dims: Array<number>, keepdims: boolean): LazyTensor
  prod(dims: Array<number>, keepdims: boolean): LazyTensor
  mean(dims: Array<number>, keepdims: boolean): LazyTensor
  max(dims: Array<number>, keepdims: boolean): LazyTensor
  min(dims: Array<number>, keepdims: boolean): LazyTensor
  reshape(shape: Array<number>): LazyTensor
  permute(dims: Array<number>): LazyTensor
  slice(ranges: Array<Array<number>>): LazyTensor
  concat(other: LazyTensor, dim: number): LazyTensor
  broadcastTo(shape: Array<number>): LazyTensor
  stopGradient(): LazyTensor
  checkpoint(): LazyTensor
  vmap(x: LazyTensor, batchedX: LazyTensor, dim: number): LazyTensor
  adamwStep(grad: LazyTensor, m: LazyTensor, v: LazyTensor, lr: LazyTensor, c1: LazyTensor, c2: LazyTensor, beta1: number, beta2: number, eps: number, weightDecay: number): LazyTensor
  adamwOut(index: number): LazyTensor
  sgdStep(grad: LazyTensor, velocity: LazyTensor, first: LazyTensor, lr: LazyTensor, momentum: number, dampening: number, nesterov: boolean, weightDecay: number): LazyTensor
  sgdOut(index: number): LazyTensor
}

export declare class NativeKvPool {
  constructor(layers: number, kvHeads: number, headDim: number, maxTokens: number, blockSize?: number | undefined | null, device?: string | undefined | null)
  get capacity(): number
  get freeBlocks(): number
  get cachedBlocks(): number
  makeSequence(): NativeKvSequence
}

export declare class NativeKvSequence {
  get cursor(): number
  release(): void
  prefillMatch(tokens: Array<number>): number
}

export declare class NativeTensor {
  get shape(): Array<number>
  get dtype(): string
  get device(): string
  get bytes(): number
  dispose(): void
  readback(token?: CancellationToken | undefined | null): Promise<ArrayBuffer>
}

export declare class NativeTokenizer {
  static fromFile(path: string, parseSpecials: boolean): NativeTokenizer
  static fromJson(json: string, parseSpecials: boolean): NativeTokenizer
  static train(config: NativeTrainConfig, parseSpecials: boolean, progress: (event: [number, number]) => void, progressEveryBytes: number): Promise<NativeTokenizer>
  get vocabSize(): number
  tokenToId(token: string): number | null
  idToToken(id: number): string | null
  save(path: string): void
  encode(text: string): Uint32Array
  encodeBatch(texts: Array<string>): Promise<Array<Uint32Array>>
  encodeTensor(text: string, device?: string | undefined | null): LazyTensor
  encodeBatchTensor(texts: Array<string>, padding: NativePadding, truncation: NativeTruncation, device?: string | undefined | null): Promise<LazyTensor>
  decode(ids: Array<number>): string
  decodeBatch(ids: Array<Array<number>>): Array<string>
}

export declare function compile(roots: Array<LazyTensor>): CompiledProgram

export declare function compileDecode(roots: Array<LazyTensor>, window?: number | undefined | null): DecodeProgram

export declare function evalLazy(tensors: Array<LazyTensor>, token?: CancellationToken | undefined | null): Promise<Array<NativeTensor>>

export declare function externalMemoryBytes(): number

export declare function grad(loss: LazyTensor, wrt: Array<LazyTensor>): Array<LazyTensor>

export declare function isDeviceAvailable(device: string): boolean

export declare function loadTensors(path: string, device?: string | undefined | null, token?: CancellationToken | undefined | null): Promise<[Array<string>, Array<NativeTensor>]>

export declare const enum NativeDType {
  F32 = 'f32',
  F64 = 'f64',
  I64 = 'i64',
  U8 = 'u8',
  U32 = 'u32',
  F16 = 'f16'
}

export interface NativePadding {
  tag: string
  padId?: number
  maxLength?: number
}

export interface NativeTrainConfig {
  model: string
  vocabSize: number
  minFrequency: number
  specialTokens: Array<string>
  source: NativeTrainSource
}

export interface NativeTrainSource {
  tag: string
  paths?: Array<string>
  texts?: Array<string>
}

export interface NativeTruncation {
  tag: string
  maxLength?: number
}

export declare function reportExternalMemory(bytes: number): void

export declare function saveTensors(path: string, names: Array<string>, tensors: Array<LazyTensor>, token?: CancellationToken | undefined | null): Promise<void>
